### ISSUE TITLE
创建tfrecord，报错索引值太多 

### ISSUE THREAD

**Issue by xiaopojizu123** [shenxiaofei715/efficientdet#2]
按照readme提供的输入进去进行数据转换，出现如下错误，请问老哥应该怎么解决？

C:\Anaconda3\python.exe C:/makelabel/efficientdet-master/dataset/create_tfrecord.py
I0409 21:01:34.563193 11168 create_tfrecord.py:149] writing to output path: C:\Users\LiMengdi\Desktop\myself_vocdata\tfdata
Traceback (most recent call last):
  File "C:/makelabel/efficientdet-master/dataset/create_tfrecord.py", line 194, in <module>
    tf.app.run(main)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Anaconda3\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\Anaconda3\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "C:/makelabel/efficientdet-master/dataset/create_tfrecord.py", line 187, in main
    tf_record_num_shards=2,img_format=".jpg")
  File "C:/makelabel/efficientdet-master/dataset/create_tfrecord.py", line 160, in create_tf_record_from_xml
    img_height,img_width,xmin,ymin,xmax,ymax,category_ids=read_xml_gtbox_and_label(xml)
  File "C:/makelabel/efficientdet-master/dataset/create_tfrecord.py", line 80, in read_xml_gtbox_and_label
    xmin=(gtbox_label[:,0:-1:2].min(axis=1)/img_width).tolist()
IndexError: too many indices for array

Process finished with exit code 1

**Comment by 15241192958** [comment]
我也遇到了同样的问题，请问您解决了吗

**Comment by 15241192958** [comment]
我已经解决了这个问题，或许对您有帮助
对于没有检测框的图片需要做一下空值判断line 80
            if gtbox_label.shape[0]==0:

**Comment by czy112** [comment]
> 我已经解决了这个问题，或许对您有帮助
> 对于没有检测框的图片需要做一下空值判断line 80
> if gtbox_label.shape[0]==0:请问后面写什么呢
